version: "3.8"

services:
   node:
    image: node:18.7.0-alpine3.16
    container_name: web-node
    env_file:
      - .env
    working_dir: /application
    tty: true
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    ports:
      - ${NODE_PORT}:${NODE_PORT}
      - ${VITE_PORT}:${VITE_PORT}
    restart: unless-stopped